# Generated by Django 4.0.2 on 2022-02-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0003_address_remove_customuser_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_price', models.IntegerField()),
                ('menu_item', models.ManyToManyField(to='Restaurants.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started_on', models.DateField()),
                ('logo', models.ImageField(default='restaurant_logo/default-restaurant-logo.jpg', upload_to='restaurant_logo/')),
                ('speciality', models.CharField(blank=True, choices=[('indian', 'Indian'), ('chinese', 'Chinese'), ('deserts', 'Deserts')], max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.address')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.menu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
