# Generated by Django 4.0.2 on 2022-02-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_alter_restaurantprofile_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant', to='Restaurants.menu'),
        ),
    ]
