# Generated by Django 4.0.2 on 2022-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_alter_restaurantprofile_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_item',
            field=models.ManyToManyField(related_name='menu', to='Restaurants.FoodItem'),
        ),
    ]
