# Generated by Django 4.0.2 on 2022-02-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_alter_menu_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_price',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
