# Generated by Django 4.0.2 on 2022-02-06 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurants', '0005_remove_menu_menu_item_price_fooditem_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
