# Generated by Django 4.0.2 on 2022-02-07 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurants', '0007_alter_restaurantprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
