# Generated by Django 4.0.2 on 2022-02-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurants', '0001_initial'),
        ('Accounts', '0003_address_remove_customuser_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Others')], max_length=100)),
                ('dob', models.DateField()),
                ('profile_picture', models.ImageField(default='user_profile_pictures/default-profile-picture.jpg', upload_to='user_profile_pictures/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_food_price', models.IntegerField()),
                ('temp_address', models.TextField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile')),
                ('menu_food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.fooditem')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurantprofile')),
            ],
        ),
    ]
