# Generated by Django 4.0.2 on 2022-02-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0005_remove_menu_menu_item_price_fooditem_food_price'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile'),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='menu_food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.fooditem'),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurantprofile'),
        ),
    ]
